### ISSUE TITLE
优化标题多行显示

### ISSUE THREAD

**Issue by Sielier** [XiaoLinXiaoZhu/XX-Mod-Manager#2]
优化标题多行显示
![image](https://github.com/user-attachments/assets/9be7a1cb-1142-4004-b2c7-4135a380da35)

**Comment by XiaoLinXiaoZhu** [comment]
mod卡片应该主要是通过封面来区分而非名称，且拥有mod描述你应该将更多的细节内容放到描述里面而非标题。

至于侧边栏不可换行，主要是一开始为了使得页面的内容简洁所以说固定为20px，不过我在 0.3.2 的版本里面增加了过于长的标题的支持。

但是我仍然不推荐取这么长的名字，不论是为了便于文件管理还是显示在mod管理器中。

**Comment by Sielier** [comment]
其实你可以把紧凑模式改成列表模式，事实上MOD配上预览图对用户侧是很麻烦的事，mod作者一般不会去添加，用户也只是为了图个方便，没动力去打开游戏截图保存，有些用户甚至截图都不会，所以还是文字更为清楚明了

**Comment by XiaoLinXiaoZhu** [comment]
> 其实你可以把紧凑模式改成列表模式，事实上MOD配上预览图对用户侧是很麻烦的事，mod作者一般不会去添加，用户也只是为了图个方便，没动力去打开游戏截图保存，有些用户甚至截图都不会，所以还是文字更为清楚明了

所以说设计了可以直接从网页中拖拽图片设置封面。在你下载mod的时候：
1. 点击下载 
2. 将mod压缩包拖到程序中 
3. 编辑mod信息，填充来源链接 
4. 将网站中提供的预览图片拖拽到卡片上，完成封面设置。

mod配上预览图本身就是顺手的事情，mod作者填不填加无所谓，也不用所谓的截图保存。

文字绝对不是清楚明了的方式，人眼识别图片的速度可是比文字快好几倍。
