### ISSUE TITLE
增加窗口最小化按钮

### ISSUE THREAD

**Issue by Sielier** [XiaoLinXiaoZhu/XX-Mod-Manager#3]

**Comment by XiaoLinXiaoZhu** [comment]
![image](https://github.com/user-attachments/assets/4324ae7b-9e26-4365-8ce5-ec606ea6bbfb)

我并不认为多一个按钮会比这个方便多少……

**Comment by Sielier** [comment]
这就有点歪理了，这是Windows，本来左上角返回键作为关闭就反人类了，最小化这玩意还要靠二级菜单，那我说你把关闭键干掉也用二级菜单也不会麻烦多少，你赞同吗？没必要为了UI而UI，绝区零的UI设计本身就是反Windows键鼠操作逻辑的，咱们可以吸收风格，灵活应用，没必要那么死板
